backend:
  name: github
  repo: Reego/multipla-site
  branch: master
media_library:
  name: cloudinary
  config:
    cloud_name: dvfbk5hsh
    api_key: 371112618454942
collections:
    - label: Files
      name: file
      files:
        - name: configuration
          label: "Configuration"
          file: static/assets/config.md
          delete: false
          fields:
            - { name: homeDisplayTitle, label: "Página principal - Título", widget: string, require: true }
            - { name: homeDisplayText, label: "Página principal - Texto", widget: string, require: true }
            - { name: homeDisplayImage, label: "Página principal - Imagem", widget: image, require: true }
            - { name: homeServicesTitle, label: "Serviços - Título", widget: string, require: true }
            - { name: homeServicesDescription, label: "Serviços - Descrição", widget: string, require: true }
            - label: "Serviços"
              name: services
              widget: list
              fields:
                - { name: serviceTitle, label: "Serviço - Nome", widget: string, require: true }
                - { name: serviceDescription, label: "Serviço - Descrição", widget: string, require: true }
            - { name: aboutDisplayImage, label: "Sobre nós - Imagem", widget: image, require: true }
            - { name: aboutText, label: "Sobre nós - Texto", widget: string, require: true }
            - { name: contactDisplayImage, label: "Contato - Imagem", widget: image, require: true }
            - { name: contactText, label: "Contato - Texto", widget: string, require: true }
            - { name: sentDisplayImage, label: "Enviado - Imagem", widget: image, require: true }
            - { name: sentDisplayText, label: "Enviado - Texto", widget: string, require: true }
            - { name: footerText, label: "Rodapé - Texto", widget: string, require: true }


